#162163221 Setup environment for writing tests
andela/ah-frontend-athena pull request #3
Opened 2019-01-09 08:27 UTC by bibangamba

#### What does this PR do?
This PR sets up the testing environment. It enables developers to write and run; unit, integration, and end-to-end tests.
#### Description of tasks to be completed?
- install/configure the test runner (jest) and add a show coverage option
- install enzyme to help with assertions on react components and traversing those components while testing
- install and set up cypress for end to end testing
#### How can this be manually tested?
- clone the repo and checkout the `ch-tests-environment-162163221` branch
- run the tests with `npm test` or `yarn test`. for coverage, use `npm test-cov` or `yarn test-cov`
- to run end to end tests, start the server locally, then use `npm cypress:open` or `yarn cypress:open` to start cypress.
#### What are the relevant pivotal stories?
[#162163221](https://www.pivotaltracker.com/story/show/162163221)

#### Screenshots
coverage report after running tests
![image](https://user-images.githubusercontent.com/5712103/50913307-1d657c80-1445-11e9-9272-a86bd536e842.png)

cypress sample test
![image](https://user-images.githubusercontent.com/5712103/50961981-3c621e00-14da-11e9-9181-cb63913010b1.png)

2019-01-09 08:30 UTC, kafuuma commented
Why are checks failing

2019-01-09 08:31 UTC, bibangamba commented
circle ci is not set up yet @kafuuma

2019-01-09 09:05 UTC, joshtrigger approved these changes

2019-01-09 09:40 UTC, JaymesKat requested changes
@bibangamba could you exclude the cypress examples as they are adding excess files? These can be accessed on the cypress website.

2019-01-09 09:50 UTC, JaymesKat requested changes
@bibangamba Well done so far. Could you exclude these files from test coverage: `serviceWorker.js` and `index.js`
<img width="645" alt="screen shot 2019-01-09 at 12 47 00" src="https://user-images.githubusercontent.com/4680759/50891388-34887800-140d-11e9-854d-2723c6c92e22.png">

2019-01-09 11:23 UTC, Kasulejoseph approved these changes

2019-01-09 11:40 UTC, bibangamba commented
alright, will work on your feedback @JaymesKat

2019-01-09 14:18 UTC, kafuuma approved these changes

2019-01-09 16:32 UTC, bibangamba commented
Hi @JaymesKat, feedback has been implemented. please check it out.

2019-01-10 07:28 UTC, JaymesKat requested changes

2019-01-10 07:28 UTC, JaymesKat commented on .gitignore
> +/cypress
We need the cypress folder to be checked in since it includes tests which can run on CI. Only exclude the `cypress/integrations/examples/` folder

2019-01-10 07:28 UTC, JaymesKat commented on .gitignore
> +yarn.lock*
This file is needed in source control. Here is [why](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/)

2019-01-10 08:02 UTC, bibangamba commented on .gitignore
> +yarn.lock*
Thank you for the resource

2019-01-10 10:37 UTC, bibangamba commented on .gitignore
> +/cypress
thank you for pointing this out, don't think I completely understood how the tests were built

2019-01-10 11:45 UTC, JaymesKat approved these changes
Good job

2019-01-10 11:46 UTC, merged